name: markdown-lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-changelog:
    name: Lint README.md file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Lint README.md file
      uses: avto-dev/markdown-lint@v1
      with:
        args: 'README.md'
